### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by 592713711** [xmartlabs/docker-jenkins-android#5]
when i do   
docker exec -it jenkins2 /bin/bash
use apt-get  but fail

jenkins@c1ab82f19123:/$ apt-get install vim
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

but root password  unknow

What should I do?

**Comment by bryant1410** [comment]
For security concerns, this image uses a non-root user. If you just want to access to a container to install vim, then do it with user 0 (root): `docker exec -u 0 -ti jenkins bash`. If you want to use this image as a base, then change the user to root in the Dockerfile and then back to "jenkins" user.

**Comment by 592713711** [comment]
thank you very much  
solution worked for me
