### ISSUE TITLE
jenkins_home reset when i commit and run

### ISSUE THREAD

**Issue by 592713711** [xmartlabs/docker-jenkins-android#6]
hello
when i commit container and run new images
I found that the jenkins directory in the new container was reset. The old jenkins data is gone.

what should i do to commit /var/jenkins_home data

**Comment by bryant1410** [comment]
Hey. You need to use a Docker volume when you run the container, so the next time you run it you use the same data. For example, run it like:

```bash
docker run -v jenkins_data:/var/jenkins_home xmartlabs/jenkins-android
```

I also recommend you to use a volume for `/opt/android-sdk-linux`, so the Android SDK tools and libraries you install once get installed forever.

I'm gonna close this issue, but feel free to comment if you think the issue hasn't been solved.

**Comment by 592713711** [comment]
that's work for me.
thank you very mach !
